objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Information of Classes in School</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Table to hold School related details</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DynamicWaysToDealsWithCollections.cls
/**
*
*  Purpose          :	Class to fill Map with dynamic Key-Value Pair.
*
*  Created Date     :  	09/02/2022
*
*  Created By       :  	Palash Singh
*
*  Revision Logs    :  	V_1.0 - Created
*
**/
public with sharing class DynamicWaysToDealsWithCollections {
    public static Map<String, Map<String, List<Student__c>>> DynamicWaysToDealsWithCollections() {
       Map<String, Map<String, List<Student__c>>> mapOfSchoolNameWithClassNameAndRelatedStudentsDetails =
        new Map<String, Map<String, List<Student__c>>>();
            List<Student__c> studentDetailList = [SELECT ID, Name, Date_of_Birth__c, Class__c,Class__r.Name,
                                                        Class__r.School__c,Class__r.School__r.Name FROM Student__c 
                                                        WHERE Class__c != null AND Class__r.School__c != null
                                                 ];
            for (Student__c student : studentDetailList){
                if(mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.containsKey(student.Class__r.School__r.Name)){
                    mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(student.Class__r.School__r.Name);
                        if(mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(student.Class__r.School__r.Name).containsKey(student.Class__r.Name)){
                            mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(student.Class__r.School__r.Name).get(student.Class__r.Name).add(student);
                        }
                            else{
                                mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.get(student.Class__r.School__r.Name)
                                    .put(student.Class__r.Name, new List<Student__c>{student});
                            }
                }       
                else{
                    Map<String, List<Student__c>> classandStudent = new Map<String,List<Student__c>>();
                    if(classandStudent.get(student.Class__r.Name)==null){
                        classandStudent.put(student.Class__r.Name, new List<Student__c>());
                    }
                    classandStudent.get(student.Class__r.Name).add(student);
                    mapOfSchoolNameWithClassNameAndRelatedStudentsDetails.put(student.Class__r.School__r.Name,classandStudent);
                }
            }
        return mapOfSchoolNameWithClassNameAndRelatedStudentsDetails;
    }
}