objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Information of Classes in School</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c/fields/Number_of_Students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Students__c</fullName>
    <label>Number of Students</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Table to hold School related details</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/School__c/fields/Number_of_Classes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Classes__c</fullName>
    <label>Number of Classes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/School__c/fields/Number_of_Students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Students__c</fullName>
    <label>Number of Students</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CountsManagerV2.cls
/**
*
*  Purpose          :	Class to count and update Number of Students and Number of Classes on a School Record.
*
*  Created Date     :  	09/12/2022
*
*  Created By       :  	Palash Singh
*
*  Revision Logs    :  	V_1.0 - Created
*
**/
public class CountsManagerV2 {
    public void updateNoOfStudentsDetails(String schoolName){
        if(schoolName!=null){
        Map<ID,School__c> mapWithSchoolDetails = new Map<ID,School__c>();
        List<School__c> schoolDetailsList = [SELECT ID, Name FROM School__c WHERE Name=: schoolName];
        //System.debug(schoolDetailsList);
        if(schoolDetailsList.size()>0){
        for (School__c school : schoolDetailsList) {
            if (!mapWithSchoolDetails.containsKey(school.ID)){
                mapWithSchoolDetails.put(school.ID,school);
            } 
        }
        Map<ID,Integer> mapWithStudentDetails = new Map<ID,Integer>(); 
        for(Student__c student : [SELECT ID, Name, Class__r.School__c 
                                    FROM Student__c 
                                        WHERE Class__r.School__c =: mapWithSchoolDetails.Keyset()]){
            if(!mapWithStudentDetails.containsKey(student.Class__r.School__c)){
                mapWithStudentDetails.put(student.Class__r.School__c,1);
            }
            else{
                mapWithStudentDetails.put(student.Class__r.School__c,(mapWithStudentDetails.get(student.Class__r.School__c)+1));
            }
            
            
        }
        if(mapWithStudentDetails.size()>0){
            List<School__c>  noOfSchoolList = new List<School__c>();
            for(ID schoolID : mapWithStudentDetails.Keyset()){
                School__c schoolCount = new School__c();
                schoolCount.Id = schoolID;
                schoolCount.Number_of_Students__c=mapwithStudentDetails.get(schoolID);
                noOfSchoolList.add(schoolCount);
            }
            if(noOfSchoolList!= null && noOfSchoolList.size()>0){
                update noOfSchoolList;
            }
        }
        }
        else{
            System.debug('Unable to find School with the given name.');
        }
        }
        else{
            System.debug('No School Found');
        }
    }
    public void updateNoOfClassDetails(ID schoolID) {
        if(schoolID!=null){
            List<School__c> classNameList = [SELECT ID, Name,(SELECT Name FROM Classes__r) FROM School__c 
                                             WHERE School__c.ID =: schoolID];
            
            if(classNameList.size() > 0){
                
                List<School__c> noOfClassList = new List<School__c>();
                
                for(School__c classDetails : classNameList){                
                    Integer classCount = classDetails.Classes__r.size();
                    School__c schoolDetails = new School__c();
                    schoolDetails.ID = classDetails.ID;
                    schoolDetails.Number_of_Classes__c = classCount;
                    noOfClassList.add(schoolDetails);
                }
                if(noOfClassList.size() > 0){
                    update noOfClassList;
                }
            }
            else{
                System.debug('Unable to find school for given Record ID.');
            }
        }
        else{
            System.debug('Unable to find a school.');
        }        
    }
}