objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Information of Classes in School</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Table to hold School related details</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
@isTest
public without sharing class TestDataFactory 
{
    public static School__c createSchool() 
    {
        School__c school = (School__c)SmartFactory.createSObject('School__c');
        insert school;
        System.assert(school.Id != null);
        System.assert(school.Name != null);
        return school;
    }
    
    public static Class__c createClass() 
    {
        Class__c cls = (Class__c)SmartFactory.createSObject('Class__c');
        insert cls;
        System.assert(cls.Id != null);
        System.assert(cls.Name != null);
        return cls;
    }
    
    public static Student__c createStudent() 
    {
        Student__c student = (Student__c)SmartFactory.createSObject('Student__c');
        insert student;
        System.assert(student.Id != null);
        System.assert(student.Name != null);
        return student;
    }
}