objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Information of Classes in School</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Table to hold School related details</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DynamicWaysToDealsWithCollectionsTest.cls
/**
*
*  Purpose          :	Test Class for DynamicWaysToDealsWithCollections Class
*
*  Created Date     :  	10/06/2022
*
*  Created By       :  	Palash Singh
*
*  Revision Logs    :  	V_1.0 - Created
*
**/
@isTest
public class DynamicWaysToDealsWithCollectionsTest {
	@testSetup
    static void testData() {
      School__c testSchool = new School__c();
      testSchool.Name = 'Test School';
      insert testSchool;
        
      Class__c testClass1 = new Class__c();
      testClass1.Name = 'Test Class One';
      testClass1.School__c = testSchool.Id;
      insert testClass1;
        
      Student__c testStudent = new Student__c();
      testStudent.Name = 'Test Student';
      testStudent.Class__c = testClass1.Id;
      insert testStudent;
       
      Student__c testStudent1 = new Student__c();
      testStudent1.Name = 'Test Student One';
      testStudent1.Class__c = testClass1.Id;
      insert testStudent1;
    }
    @isTest
    static void myTestOne() {
        List<Student__c> expectedStudentList = [SELECT ID, Name, Class__c FROM Student__c WHERE Name Like 'Test%'];
        Map<String, Map<String, List<Student__c>>> studentList = DynamicWaysToDealsWithCollections.DynamicWaysToDealsWithCollections();
     	System.assertEquals(expectedStudentList[0].name, studentList.get('Test School').get('Test Class One')[0].name);
        System.assertEquals(expectedStudentList[1].name, studentList.get('Test School').get('Test Class One')[1].name);
    }
}